### ISSUE TITLE
16.10 Aufgabe 4

### ISSUE THREAD

**Issue by MineRickStar** [sweIhm-ws2018-19/skillproject-di-6#1]
Software Engineering Aufgabe 4, des Praktikums am 16.10.

**Comment by Asphilia** [comment]
Ich kann keine Fehler im Code finden. Gut gemacht!

**Comment by little5un** [comment]
Ich würde es genauso machen!

**Comment by SDouglas3** [comment]
Das sieht gut aus- ich denke, es ist richtig!
