### ISSUE TITLE
Aufgabe 5

### ISSUE THREAD

**Issue by SDouglas3** [sweIhm-ws2018-19/skillproject-di-6#2]
Ich habe ein Bild des Objektdiagramm auf Whatsapp hochgestellt- ich hab es auch als xml hier auf GitHub hochgeladen.
Ihr könnt es euch mal anschauen

**Comment by Asphilia** [comment]
Ich habe nichts an deiner Lösung auszusetzen.

**Comment by MineRickStar** [comment]
Das Bild ist so weit richtig.

**Comment by little5un** [comment]
Sieht richtig aus. Hätte es nicht anders gemacht!
