### ISSUE TITLE
Sequenzdiagramm für Sprint 1

### ISSUE THREAD

**Issue by Asphilia** [sweIhm-ws2018-19/skillproject-di-6#29]
Ich habe jetzt das _Sequenzdiagramm_ erstellt.
Bitte schaut doch mal rüber und _reviewt_ was ich noch ändern soll ;-)
![sequenzdiagramm sprint 1](https://user-images.githubusercontent.com/43779157/48947106-521e8280-ef30-11e8-88c9-d33894cff3e2.png)

**Comment by MineRickStar** [comment]
Schaut gut aus, bis auf den Hintergrund. lolz
