### ISSUE TITLE
Was macht die Methode

### ISSUE THREAD

**Issue by MineRickStar** [sweIhm-ws2018-19/skillproject-di-6#39]
https://github.com/sweIhm-ws2018-19/skillproject-di-6/blob/218ba3cc105394c9a5fa5214d665d79118697c3b/src/main/java/braingain/modell/Spielrunde.java#L47

Bestimmt die Methode den Höchsten hihscore, oder die Höchste Punktzahl?

**Comment by SDouglas3** [comment]
Naja, die Methode übergibt dem Handler ErgebnisBestimmen (oder so) die Namen der Gewinner eines Duells und die höchste Punktezahl. Dann kann der Handler verkünden: Mit so und so vielen Punkten hat Spieler so und so gewonnen!

**Comment by MineRickStar** [comment]
Also hat der Spieler einen Highscore und einen Punktestand und in der Klasse Spielerunde gibt es einen Methode getHighscore und die nutzt aber nicht den Highscore des Spielers, weil der nur für Einzelmodus ist?

**Comment by SDouglas3** [comment]
Der highscore des Spielers ist nur, damit der Spieler fragen kann, wie er sich verbessert hat im Vergleich zu seiner besten Runde.
Also ja.

**Comment by MineRickStar** [comment]
Gut, dann hab ich das verstanden.
