### ISSUE TITLE
Blatt 2, Aufgabe 7

### ISSUE THREAD

**Issue by Asphilia** [sweIhm-ws2018-19/skillproject-di-6#4]
Die PNG Datei ist im UML/Ü2 Ordner.
Ich bitte um Rückmeldungen.

**Comment by MineRickStar** [comment]
Sieht richtig aus, ich habe keine Fehler gefunden.

**Comment by SDouglas3** [comment]
Hast du schön gemacht!

**Comment by little5un** [comment]
Passt, denke ich!
