### ISSUE TITLE
Blatt 2, Aufgabe 8

### ISSUE THREAD

**Issue by MineRickStar** [sweIhm-ws2018-19/skillproject-di-6#7]
Das ist das Objektdiagramm zu Aufgabe 8

**Comment by MineRickStar** [comment]
![ubung 2 aufgabe 8](https://user-images.githubusercontent.com/43779009/47602835-4c428980-d9e4-11e8-9157-cd3e52e6e9f6.png)

**Comment by SDouglas3** [comment]
Ich konnte keinen Fehler finden

**Comment by MineRickStar** [comment]
Wir warten noch auf eine Antwort von Frau Socher bezüglich der Attribute

**Comment by little5un** [comment]
Hätte ich nicht anders gemacht!

**Comment by MineRickStar** [comment]
![blatt 2 aufgabe 8](https://user-images.githubusercontent.com/43779009/47648735-2996a900-db7b-11e8-9db7-1becc50c42c1.png)

Hab ich jetzt aktualisiert, hoffentlich passts so.
