### ISSUE TITLE
Blatt 2, Aufgabe 9

### ISSUE THREAD

**Issue by Asphilia** [sweIhm-ws2018-19/skillproject-di-6#8]
Sequenzdiagramm für Aufgabe 9 ist jetzt hochgeladen.

**Comment by Asphilia** [comment]
![blatt 2 aufgabe 9-sequenzdiagram](https://user-images.githubusercontent.com/43779157/47602848-77c57400-d9e4-11e8-8d2a-69b84a1377ac.png)

**Comment by MineRickStar** [comment]
Schaut gut aus, Lebenslinien müssten aber nicht bei allen am Anfang starten.

**Comment by SDouglas3** [comment]
https://moodle.hm.edu/mod/resource/view.php?id=153760

Auf den Lehrseiten für Sequenzdiagrammen fangen die Lebenslinien aber alle am Anfang an.

Hast du schön gemacht!

**Comment by little5un** [comment]
Sieht gut aus!
